### PR TITLE
more url friendly test report filename

### PR DESCRIPTION
**Pull request by zeroryu**
Allows for better compatibility with circle ci artifact uploads.

ParentClass::ChildClass::ExampleController will generate parent_class/child_class/example_controller-TEST.xml

### CODE REVIEW

**Comment by nwjsmith** [comment]
Since this is a breaking change, could you make it opt-in? An option on `Minitest::CI` would suffice.

**Review by zeroryu — COMMENTED** [review]
converted the breaking change to be an option as suggested

**Comment by zzak** [comment]
The logic is a little confusing here, saying `use_module_name` to default `true` but still uses the old name.

**Review by zeroryu — COMMENTED** [review]
reverse the naming to be more of an intentional set to true to change behavior instead of set to false as previous ones

**Comment by zzak** [comment]
@zeroryu Great! Could you write a test and then squash your commits?

**Comment by zzak** [comment]
You may want to take a look at #16, thank you for the inspiration @zeroryu!

**Pull request closed without merging**
